const products = [
  {
    _id: '1',
    name: 'Addidas',
    image: '/images/alex-quezada-qAyOt0aGsCo-unsplash.jpg',
    description: 'Red Shoe 16ch high heels',
    brand: 'ellen',
    category: 'high heels',
    price: 16.99,
    countInStock: 7,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Nike',
    image: '/images/gavin-allanwood-ndpX28miBtE-unsplash.jpg',
    description: 'Blue running shoes',
    brand: 'Nike',
    category: 'Running',
    price: 59.99,
    countInStock: 5,
    rating: 4.2,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Puma',
    image: '/images/kier-in-sight-archives-b4Xk6bzgQWU-unsplash.jpg',
    description: 'White and black sneakers',
    brand: 'Puma',
    category: 'Sneakers',
    price: 39.99,
    countInStock: 10,
    rating: 4.7,
    numReviews: 18,
  },
  {
    _id: '4',
    name: 'Converse',
    image: '/images/mostafa-mahmoudi-uianIkmhuvk-unsplash.jpg',
    description: 'Classic Chuck Taylor All Star',
    brand: 'Converse',
    category: 'Casual',
    price: 29.99,
    countInStock: 15,
    rating: 4.4,
    numReviews: 9,
  },
];

export default products;
